version: "3.7"
services:
    app:
        build: ./
        ports:
            - "8888:8888"
        depends_on:
            - db
            - redis
        volumes:
            - ./:/go/src/app
        env_file:
            - ./.env
    db:
        image: mariadb:latest
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql
    redis:
        image: redis:latest
        ports:
            - "6379:6379"
volumes:
    db_data: